weak12kprompt = {
    "instruction": {
        "role": "system",
        "content": "请一步一步地推理，并将你的最终答案写在\\boxed{{}}中。当原问题可以回答时，请用“现在我们可以回答这个问题:”来开始子问题。",
    },
    "answer_prefix": "让我们一步步思考来解决这个问题:",
    "question_prefix": "\n步骤%d. **",
    "question_postfix": "**",
    "overall_question_prefix": "现在我们可以回答这个问题:",
    "useful_instrution": "\n给出一个问题及其对应的子问题和答案。判断这个过程是否有助于回答问题。输出'是'或'否'，并给出理由。\n\n问题 1:",
    "useful_question_prefix": "**",
    "useful_examples_prefix": "\n给出一个问题及其对应的子问题和答案。判断这个过程是否有助于回答问题。输出'是'或'否'，并给出理由。\n\n问题 1:",
    "yes_token": " 是,",
    "no_token": " 否,",
    "interactive_examples": [],
    "useful_prefix": "上面这个问题的解答过程是否有利于我们回答这个问题吗?",
    "useful_instrution_PRM": "问题 1:",
    "useful_prefix_PRM": "\n\n",
    "stop": ["\n\n", "\n步骤"],
}
schoolprompt = {
    "instruction": {
        "role": "system",
        "content": "请一步一步地推理，并将你的最终答案写在\\boxed{{}}中。如果有多个答案，用','隔开。当原问题可以回答时，请用“现在我们可以回答这个问题:”来开始子问题。",
    },
    "answer_prefix": "让我们一步步思考来解决这个问题:",
    "question_prefix": "\n步骤%d. **",
    "question_postfix": "**",
    "overall_question_prefix": "现在我们可以回答这个问题:",
    "useful_instrution": "\n给出一个问题及其对应的子问题和答案。判断这个过程是否有助于回答问题。输出'是'或'否'，并给出理由。\n\n问题 1:",
    "useful_question_prefix": "**",
    "useful_examples_prefix": "\n给出一个问题及其对应的子问题和答案。判断这个过程是否有助于回答问题。输出'是'或'否'，并给出理由。\n\n问题 1:",
    "yes_token": " 是,",
    "no_token": " 否,",
    "interactive_examples": [],
    "useful_prefix": "上面这个问题的解答过程是否有利于我们回答这个问题吗?",
    "useful_instrution_PRM": "问题 1:",
    "useful_prefix_PRM": "\n\n",
    "stop": ["\n\n", "\n步骤"],
}
gaokaoprompt = {
    "instruction": {
        "role": "system",
        "content": "请一步一步地推理，在“A”, “B”, “C”, “D”四个选项中选择出正确的答案。，并将你的最终答案写在\\boxed{{}}中。当原问题可以回答时，请用“现在我们可以回答这个问题:”来开始子问题。",
    },
    "answer_prefix": "让我们一步步思考来解决这个问题:",
    "question_prefix": "\n步骤%d. **",
    "question_postfix": "**",
    "overall_question_prefix": "现在我们可以回答这个问题:",
    "useful_instrution": "\n给出一个问题及其对应的子问题和答案。判断这个过程是否有助于回答问题。输出'是'或'否'，并给出理由。\n\n问题 1:",
    "useful_question_prefix": "**",
    "useful_examples_prefix": "\n给出一个问题及其对应的子问题和答案。判断这个过程是否有助于回答问题。输出'是'或'否'，并给出理由。\n\n问题 1:",
    "yes_token": " 是,",
    "no_token": " 否,",
    "interactive_examples": [],
    "useful_prefix": "上面这个问题的解答过程是否有利于我们回答这个问题吗?",
    "useful_instrution_PRM": "问题 1:",
    "useful_prefix_PRM": "\n\n",
    "stop": ["\n\n", "\n步骤"],
}
weak12k_usefulprompt = {
    "input": "给定一个问题和一些子问题,确定最后一个子问题是否有利于回答这个问题吗?.输出“是”或“否”,以及一个原因.\n\n",
    "question_prefix": "问题 : ",
    "subquestion_prefix": "问题 1.{}:",
    "new_subquestion_prefix": "新问题 1.{}:",
    "useful_prefix": "新的子问题是否有利于回答这个问题?",
    "input_PRM": "针对下面的问题可以分解成多个子问题\n",
    "useful_prefix_PRM": "\n",
    "yes_token": " 是,",
    "no_token": " 否,",
}

gsm8kprompt = {
    "instruction": {
        "role": "system",
        "content": "Please reason step by step, and write your final answer in \\boxed{{}}. When the original question can be answered, please start the sub-problem with 'Now we can answer this question:'.",
    },
    "answer_prefix": "Let's think step by step to solve this problem:",
    "question_prefix": "\nStep %d. **",
    "question_postfix": "**",
    "overall_question_prefix": "Now we can answer this question:",
    "useful_instrution": "\nProvide a question and its corresponding sub-questions and answers. Determine whether this process helps to answer the question. Output 'Yes' or 'No', and give a reason.\n\nQuestion 1:",
    "useful_question_prefix": "**",
    "useful_examples_prefix": "\nProvide a question and its corresponding sub-questions and answers. Determine whether this process helps to answer the question. Output 'Yes' or 'No', and give a reason.\n\nQuestion 1:",
    "yes_token": " Yes,",
    "no_token": " No,",
    "interactive_examples": [],
    "useful_prefix": "Is the solution process for the above question helpful for us to answer this question?",
    "useful_instrution_PRM": "Question 1:",
    "useful_prefix_PRM": "\n\n",
    "stop": ["\n\n", "\nStep"],
}
mathprompt = {
    "instruction": {
        "role": "system",
        "content": "Please reason step by step,  organize your thoughts into a complete answer. If there are multiple questions in the problem, answer each one in turn, separated by commas, and write the final answer in \\boxed{}. When the original question can be answered, please start the sub-problem with 'Now we can answer this question:'.",
    },
    "answer_prefix": "Let's think step by step to solve this problem:",
    "question_prefix": "\nStep %d. **",
    "question_postfix": "**",
    "overall_question_prefix": "Now we can answer this question:",
    "useful_instrution": "\nProvide a question and its corresponding sub-questions and answers. Determine whether this process helps to answer the question. Output 'Yes' or 'No', and give a reason.\n\nQuestion 1:",
    "useful_question_prefix": "**",
    "useful_examples_prefix": "\nProvide a question and its corresponding sub-questions and answers. Determine whether this process helps to answer the question. Output 'Yes' or 'No', and give a reason.\n\nQuestion 1:",
    "yes_token": " Yes,",
    "no_token": " No,",
    "interactive_examples": [],
    "useful_prefix": "Is the solution process for the above question helpful for us to answer this question?",
    "useful_instrution_PRM": "Question 1:",
    "useful_prefix_PRM": "\n\n",
    "stop": ["\nStep"],
}
gsm8k_usefulprompt = {
    "input": "Given a question and some sub-questions, determine whether the last sub-question is helpful in answering the question. Output 'Yes' or 'No', and provide a reason.\n\n",
    "question_prefix": "Question: ",
    "subquestion_prefix": "Sub-question 1.{}:",
    "new_subquestion_prefix": "New sub-question 1.{}:",
    "useful_prefix": "Is the new sub-question helpful in answering the question?",
    "input_PRM": "For the following question, it can be broken down into multiple sub-questions\n",
    "useful_prefix_PRM": "\n",
    "yes_token": " Yes,",
    "no_token": " No,",
}

aquaprompt = {
    "instruction": {
        "role": "system",
        "content": "Please reason step by step, choose the option from “A”, “B”, “C”, “D”, “E” that is closest to your answer and write your final answer in \\boxed{{}}. When the original question can be answered, please start the sub-problem with 'Now we can answer this question:'.",
    },
    "answer_prefix": "Let's think step by step to solve this problem:",
    "question_prefix": "\nStep %d. **",
    "question_postfix": "**",
    "overall_question_prefix": "Now we can answer this question:",
    "useful_instrution": "\nProvide a question and its corresponding sub-questions and answers. Determine whether this process helps to answer the question. Output 'Yes' or 'No', and give a reason.\n\nQuestion 1:",
    "useful_question_prefix": "**",
    "useful_examples_prefix": "\nProvide a question and its corresponding sub-questions and answers. Determine whether this process helps to answer the question. Output 'Yes' or 'No', and give a reason.\n\nQuestion 1:",
    "yes_token": " Yes,",
    "no_token": " No,",
    "interactive_examples": [],
    "useful_prefix": "Is the solution process for the above question helpful for us to answer this question?",
    "useful_instrution_PRM": "Question 1:",
    "useful_prefix_PRM": "\n\n",
    "stop": ["\n\n", "\nStep"],
}
